services:
  gophish:
    container_name: gophish-container
    image: gophish/gophish
    ports:
      - 8080:3333

# notes :
# to get username & password follow the following command
# docker logs -f gophish-container